// Generated by Tools/NN/ExportAttackTargetReach.py. Do not hand-edit.
// Original GT frame-0 foot midpoint -> saved hit target, horizontal cm.
// Source paths/hashes and raw coordinates: Docs/AttackTargetReach.json.
namespace ProphecyAttackTargetReach
{
struct FEntry { FName Attack; double RadiusCm; };
static const FEntry Entries[] = {
    { TEXT("jabL"), 89.401316851344 },
    { TEXT("jabR"), 88.382796295631 },
    { TEXT("hookL"), 76.995748184193 },
    { TEXT("hookR"), 62.001169364759 },
    { TEXT("overL"), 72.919153424900 },
    { TEXT("overR"), 86.844319023684 },
    { TEXT("headbutt"), 63.169221385026 },
    { TEXT("kickL"), 117.864773417798 },
    { TEXT("kickR"), 120.004167178596 },
    { TEXT("slashL"), 129.384277628299 },
    { TEXT("slashR"), 96.622901323165 },
    { TEXT("slashLD"), 122.346522107080 },
    { TEXT("slashRD"), 89.104313378674 },
    { TEXT("slashLU"), 123.794312633538 },
    { TEXT("slashRU"), 89.195161776802 },
    { TEXT("pike"), 140.407606580155 },
};
}
