"""Generate the small, startup-only upper seed from the authored neutral idle.

Core joints retain local rotations; hands and elbow frames are stored relative
to the pelvis so the same idle can initialize any lower seed/root heading.
Does not export or change a network/checkpoint.
"""
import argparse
import hashlib
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--stepper-root', type=Path, default=Path(r'C:\Users\singerie\Documents\Cursor\stepper'))
    parser.add_argument('--clip', default='training/slashes2/walk_run_sword_prep/authored_pruned_npz/walk_omni/M_Neutral_Stand_Idle_Loop.npz')
    parser.add_argument('--frame', type=int, default=0)
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[2]/'Source/GameAnimationSample3/Private/ProphecyUpperIdleSeed.h')
    args = parser.parse_args()
    sys.path.insert(0, str(args.stepper_root))
    import torch
    from training.ik import ik_core as tl
    from training.ik import train_upper_pose_autoencoder as upper
    path = args.stepper_root/args.clip
    clip = tl.MotionClip(path, upper.motion_config(), cyclic_animation=True)
    names = {n:i for i,n in enumerate(clip.body_names)}
    frame = args.frame
    pelvis = names['pelvis']
    inv = clip.global_rot[frame, pelvis].T
    values = [clip.local_rot6[frame,names[n]] for n in upper.CORE_BONES]
    for _,arm,_,hand in upper.ARM_SPECS:
        values.extend([
            (clip.global_pos[frame,names[hand]]-clip.global_pos[frame,pelvis]) @ inv,
            tl.rotmat_to_6d(clip.global_rot[frame,names[hand]] @ inv),
            tl.rotmat_to_6d(clip.global_rot[frame,names[arm]] @ inv),
        ])
    seed = torch.cat(values).float()
    assert seed.numel()==90 and torch.isfinite(seed).all()
    # Check the stored arm data round trips through its original pelvis.
    for side,(_,arm,_,hand) in enumerate(upper.ARM_SPECS):
        offset = 60+15*side
        recovered = seed[offset:offset+3] @ clip.global_rot[frame,pelvis]+clip.global_pos[frame,pelvis]
        assert torch.max(torch.abs(recovered-clip.global_pos[frame,names[hand]]))<1.e-5
        print(hand, 'authored world metres', clip.global_pos[frame,names[hand]].tolist())
    def literal(v):
        text=format(float(v),'.9g')
        if '.' not in text and 'e' not in text:text+='.'
        return text+'f'
    rows=[', '.join(literal(v) for v in seed[i:i+6])+',' for i in range(0,90,6)]
    args.output.write_text('#pragma once\n// Generated by Tools/NN/ExportProphecyUpperIdleSeed.py; do not edit values manually.\n'
        +'// M_Neutral_Stand_Idle_Loop, frame '+str(frame)+', SHA256 '+hashlib.sha256(path.read_bytes()).hexdigest()+'\n'
        +'// First 60: local core rotations. Arms: pelvis-relative position / hand rotation / elbow frame.\n'
        +'namespace ProphecyUpperIdleSeed\n{\ninline constexpr float PelvisLocal[90] = {\n    '+'\n    '.join(rows)+'\n};\n}\n')
    print('Wrote',args.output)


if __name__=='__main__':main()
