#include "CoreMinimal.h"
#include "Editor.h"
#include "Engine/Blueprint.h"
#include "EdGraph/EdGraph.h"
#include "EdGraphSchema_K2.h"
#include "K2Node_CallFunction.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "ScopedTransaction.h"
#include "HAL/IConsoleManager.h"

namespace
{
// Explicit one-time migration, never run at startup. Old fractional Hit scores
// have no time equivalent, so their unconnected pins become the requested zero.
void UpgradeDefenseDelays()
{
    if(!GEditor || GEditor->PlayWorld)return;
    auto* BP=LoadObject<UBlueprint>(nullptr,TEXT("/Game/_mygame/locomotion/BP_ProphecyManualPoseAgent.BP_ProphecyManualPoseAgent"));
    if(!BP)return;
    const TSet<FName> Families={TEXT("Headbutt"),TEXT("HookL"),TEXT("HookR"),TEXT("JabL"),TEXT("JabR"),TEXT("KickL"),TEXT("KickR"),
        TEXT("OverL"),TEXT("OverR"),TEXT("Pike"),TEXT("SlashL"),TEXT("SlashLD"),TEXT("SlashLU"),TEXT("SlashR"),TEXT("SlashRD"),TEXT("SlashRU")};
    TArray<UEdGraph*> Graphs;BP->GetAllGraphs(Graphs);TArray<UK2Node_CallFunction*> Delays,Velocity;
    for(auto* G:Graphs)for(UEdGraphNode* Base:G->Nodes)
    {
        auto* N=Cast<UK2Node_CallFunction>(Base);if(!N)continue;
        const FName Name=N->FunctionReference.GetMemberName();
        if(Name==TEXT("SetParryStartHitThresholds") || Name==TEXT("SetDodgeStartHitThresholds"))
        {
            for(auto* P:N->Pins)if(Families.Contains(P->PinName) && !P->LinkedTo.IsEmpty())
            {UE_LOG(LogTemp,Error,TEXT("Defense delay upgrade: connected old threshold %s.%s requires explicit conversion"),*N->GetName(),*P->PinName.ToString());return;}
            Delays.Add(N);
        }
        else if(Name==TEXT("SetDefenseHalfAttackHorizontalVelocity"))Velocity.Add(N);
    }
    FScopedTransaction Tx(NSLOCTEXT("Prophecy","DefenseTickDelays","Replace defense Hit thresholds with tick delays"));
    BP->Modify();int Pins=0;
    for(auto* N:Delays)
    {
        N->GetGraph()->Modify();N->Modify();
        const auto OldPins=N->Pins;
        for(auto* P:OldPins)if(Families.Contains(P->PinName))
        {
            if(P->bOrphanedPin){N->RemovePin(P);continue;}
            P->PinType.PinCategory=UEdGraphSchema_K2::PC_Int;P->PinType.PinSubCategory=NAME_None;
            P->DefaultValue=TEXT("0");P->AutogeneratedDefaultValue=TEXT("0");++Pins;
        }
        N->ReconstructNode();
    }
    for(auto* N:Velocity){N->GetGraph()->Modify();N->Modify();N->ReconstructNode();}
    FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified(BP);
    FKismetEditorUtilities::CompileBlueprint(BP,EBlueprintCompileOptions::SkipGarbageCollection);
    const FString Report=FString::Printf(TEXT("delay_nodes=%d integer_pins=%d velocity_nodes=%d status=%d saved=0\n"),Delays.Num(),Pins,Velocity.Num(),int(BP->Status));
    FFileHelper::SaveStringToFile(Report,*(FPaths::ProjectSavedDir()/TEXT("Diagnostics/DefenseTickDelays20261008/migration.txt")));
    UE_LOG(LogTemp,Display,TEXT("Defense delay upgrade: %s"),*Report);
}
FAutoConsoleCommand DefenseTickDelayUpgradeCommand(TEXT("Prophecy.Editor.UpgradeDefenseTickDelays"),TEXT("Replace saved unconnected Hit thresholds with integer zero delays and refresh root-velocity pin; preserves execution and leaves unsaved."),FConsoleCommandDelegate::CreateStatic(&UpgradeDefenseDelays));
}
