from pathlib import Path
import json
p=Path(__file__).parent;root=p.parents[2];d=json.loads((p/'periodic_analysis.json').read_text())
b=d['traces']['before'];a=d['traces']['after']
entry=f'''**Periodic idle limits fixed, September30:** all equivalent idle intervals (0,+/-360,+/-720 degrees...) now share the same damping/recoil behavior. Authored motion stays unwrapped for continuity, while damping chooses the nearest equivalent allowed interval and spring error is the shortest signed excess beyond it. Entering any valid idle interval clears correction/velocity. Recoil velocity directed away from a newly selected nearest boundary is discarded; its step cannot overshoot through that boundary. This velocity belongs only to the correction spring, not arm inertia. Debug color/labels use the same wrapped idle-relative angle. No Blueprint tuning, reference/timing changes, new inference, retained-layout changes or disabled pose work.

Matched350-tick current Run replay at the user's wrist strength60, limit5, damping10, hold2.5/blend0.5: at251 proposed {a['samples']['251']['proposed']:.6f}degrees, corrected wrist changes {b['samples']['251']['actual']:.6f}→{a['samples']['251']['actual']:.6f}; at269 {b['samples']['269']['actual']:.6f}→{a['samples']['269']['actual']:.6f}degrees. Every in-limit proposal is now preserved (maximum angular correction {a['max_correction_for_within_limit_proposal']:.9f}degrees, formerly {b['max_correction_for_within_limit_proposal']:.6f}). All six arm joint positions match within {d['position_error_cm']:.9f}cm, left wrist within {d['left_rotation_error_degrees']:.9f}degrees, all transforms finite. Weak recoil still permits legitimate overshoot; user will tune it. Evidence Saved/Diagnostics/ArmsDrag260/wrap_periodic_before/after and periodic_analysis.json. Owned PIE ended/audits reset; no asset save/full suite/push.

'''
path=root/'Docs/ArmRepellantCone.md';s=path.read_text(encoding='utf-8');s=s.replace('### Wrist twist recoil\n\n','### Wrist twist recoil\n\n'+entry,1);s=s.replace('**Run wrap diagnosis, September30 (no runtime change):**','**Earlier run wrap diagnosis, September30 (fixed above):**',1);path.write_text(s,encoding='utf-8')
path=root/'ProjectJournal.md';s=path.read_text(encoding='utf-8');summary=f'''- **Periodic wrist idle limits fixed (September30):** damping/recoil now select the nearest equivalent idle interval instead of unwinding accumulated revolutions toward absolute0. Clears obsolete recoil velocity when it would push away from the newly selected boundary, limits spring step to that boundary, and wraps debug labels/color consistently. No tuning changes (current strength60/limit5/damping10/hold2.5/blend0.5), no extra inference/disabled work/layout changes. Same350-tick Run replay at251 output {b['samples']['251']['actual']:.3f}→{a['samples']['251']['actual']:.3f}degrees, matching the in-limit NN proposal; all in-limit proposals preserved, arm positions and left wrist unchanged. Remaining weak-recoil overshoot is tuning, left to user. Evidence Saved/Diagnostics/ArmsDrag260/periodic_analysis.json, wrap_periodic_before/after captures. Owned PIE ended/audits0, no BP edits/save/full suite/push. [Contract](Docs/ArmRepellantCone.md).

''';s=s.replace('## Resume here\n\n','## Resume here\n\n'+summary,1);s=s.replace('**Run wrist wrapping diagnosed (September30, not fixed):**','**Earlier run wrist wrapping diagnosis (September30; now fixed above):**',1);path.write_text(s,encoding='utf-8')
print('Recorded periodic correction and measured verification')
