import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.HARNESS_PLAYWRIGHT_MODULE||'playwright');
const root=process.cwd(),store=path.join(root,'verification-v2',crypto.randomUUID());
await fs.mkdir(path.join(store,'snapshots'),{recursive:true});
await fs.copyFile('snapshots/snapshot_0002.json',path.join(store,'state.json'));
await fs.copyFile('snapshots/snapshot_0002.json',path.join(store,'snapshots/snapshot_0002.json'));
await fs.copyFile('snapshots/snapshot_0002.png',path.join(store,'snapshots/snapshot_0002.png'));
const python=path.resolve(root,'../../../.tools/python310/python.exe'),origin='http://127.0.0.1:8827';
let server,browser;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const startServer=async()=>{server=spawn(python,['server.py','--port','8827','--state-dir',store],{cwd:root,windowsHide:true,stdio:'ignore'});for(let i=0;i<80;i++){try{const h=await (await fetch(origin+'/health')).json();if(h.store===store)return;}catch{}await delay(100);}throw Error('Test server did not start');};
const stopServer=async()=>{if(server&&!server.killed){const done=new Promise(r=>server.once('exit',r));server.kill();await done;}};
const errors=[];
try{
 await startServer();
 const token=crypto.randomUUID();await fetch(origin+'/desktop-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});
 browser=await chromium.launch({headless:true,executablePath:process.env.HARNESS_CHROMIUM_EXECUTABLE,args:['--enable-webgl','--use-angle=swiftshader']});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/?desktopSession='+token);await page.waitForFunction(()=>recoveryLab.ready);
 await page.check('#handGizmos');await page.check('#upperarmGizmos');
 await page.evaluate(()=>recoveryLab.seek(23.503000006526904/30));
 await page.screenshot({path:'verification-v2-authored.png'});
 const authored=await page.evaluate(()=>recoveryLab.currentPose.tint);
 if(authored[1]<=authored[0])throw Error('Authored body is not green');
 await page.evaluate(()=>recoveryLab.seek(recoveryLab.model().attackSeconds+.25));
 const returning=await page.evaluate(()=>recoveryLab.currentPose.tint);
 if(returning[0]<=returning[1])throw Error('Return body is not orange');
 await page.uncheck('#phaseColors');await page.click('#start');
 const disabled=await page.evaluate(()=>recoveryLab.currentPose.tint);
 if(disabled[0]<=disabled[1])throw Error('Disabled phase colors must stay orange');
 await page.check('#phaseColors');await page.evaluate(()=>recoveryLab.seek(23.503000006526904/30));
 await delay(1300);
 const live=await (await fetch(origin+'/desktop-view')).json();
 if(!live.ok||live.state.attack!=='slashLU'||live.state.variant!==20||Math.abs(live.frame-23.5030000065)>.00001)throw Error('Desktop view does not match');
 const png=Buffer.from(await(await fetch(origin+'/desktop-view.png?sequence='+live.sequence)).arrayBuffer());
 if(crypto.createHash('sha256').update(png).digest('hex')!==live.imageSha256)throw Error('Image/state mismatch');
 const rogue=await fetch(origin+'/desktop-view',{method:'POST',headers:{'Content-Type':'application/json','X-Client-Id':'other-tab'},body:JSON.stringify({sequence:999999})});
 if(rogue.status!==403)throw Error('Another tab may overwrite the desktop');
 const inspection=await browser.newPage();await inspection.goto(origin+'/?inspection=1');await inspection.waitForFunction(()=>recoveryLab.ready);await inspection.selectOption('#attack','headbutt');await delay(400);await inspection.close();
 const still=await(await fetch(origin+'/desktop-view')).json();if(still.clientId!==live.clientId||still.state.attack!==live.state.attack)throw Error('Inspection tab stole desktop identity');
 const command=await(await fetch(origin+'/app-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:live.clientId,command:'capture_visible_trajectory'})})).json();
 let capture;for(let i=0;i<40;i++){capture=await(await fetch(origin+'/capture?id='+command.id)).json();if(!capture.pending)break;await delay(100);}
 if(capture.error||capture.fingerprint!==command.fingerprint||!capture.samples?.length)throw Error('Read-only capture failed');
 await page.click('#snapshot');await page.waitForFunction(()=>document.querySelector('#notice').textContent.startsWith('Saved snapshot_'));
 const snapshot=await page.locator('#snapshots option').nth(1).getAttribute('value');
 await Promise.all([page.waitForEvent('domcontentloaded'),page.click('#refresh')]);await page.waitForFunction(()=>window.recoveryLab?.ready);
 if(!await page.locator('#handGizmos').isChecked()||!await page.locator('#upperarmGizmos').isChecked())throw Error('Guizmo state was lost');
 await page.click('#play');await delay(7000);await page.click('#play');
 await page.selectOption('#attack','pike');await page.waitForFunction(()=>recoveryLab.model()?.clip.name==='pike');await page.click('#play');await delay(2600);await page.click('#play');
 await page.selectOption('#snapshots',snapshot);await page.waitForFunction(()=>recoveryLab.model()?.clip.name==='slashLU');
 await page.click('#removeVariant');await page.waitForFunction(()=>recoveryLab.model()?.meta.id!==20&&document.querySelector('#notice').textContent.startsWith('Permanently removed'));
 if(await page.locator('#variant option').count()!==19||!await page.locator('#floorTarget').isDisabled())throw Error('Variant was not excluded');
 await page.click('#nextVariant');await page.click('#prevVariant');
 await Promise.all([page.waitForEvent('domcontentloaded'),page.click('#refresh')]);await page.waitForFunction(()=>window.recoveryLab?.ready);
 if(await page.locator('#variant option[value="20"]').count())throw Error('Removed variant returned after refresh');
 await page.selectOption('#attack','headbutt');await page.waitForFunction(()=>recoveryLab.model()?.clip.name==='headbutt');if(!await page.locator('#floorTarget').isDisabled())throw Error('Headbutt floor rule');
 await page.screenshot({path:'verification-v2-controls.png'});
 await browser.close();browser=null;await stopServer();await startServer();
 const restarted=await(await fetch(origin+'/data/manifest.json')).json();if(restarted.clips.find(c=>c.name==='slashLU').variants.some(v=>v.id===20))throw Error('Removal lost on restart');
 if(errors.length)throw Error(errors.join('\n'));
 const report={ok:true,phaseColors:true,guizmosPersist:true,desktopIdentity:true,imageMatchesState:true,inspectionCannotPublish:true,readOnlyCaptureFrames:capture.samples.length,snapshotRestore:true,refresh:true,threePlaybackLoops:true,secondAttackPlayback:true,permanentRemovalAcrossRestart:true,userLibraryUntouched:true,errors,store};
 await fs.writeFile('verification-v2-ui.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{if(browser)await browser.close();await stopServer();}
