const fs=require('fs'),path=require('path'),R=require('C:/Users/singerie/Documents/Cursor/stepper/training/slashes2/AttackRecoveryLab/recovery.js');
const lab='C:/Users/singerie/Documents/Cursor/stepper/training/slashes2/AttackRecoveryLab',s=JSON.parse(fs.readFileSync(path.join(lab,'state.json'))),manifest=JSON.parse(fs.readFileSync(path.join(lab,'data/manifest.json'))),clip=manifest.clips.find(c=>c.name==='slashRU'),meta=clip.variants.find(v=>v.id===16),b=fs.readFileSync(path.join(lab,meta.file));
const m=R.prepare(meta,b.buffer.slice(b.byteOffset,b.byteOffset+b.length),clip,manifest.names,manifest.parents),o={duration:s.attackReturnTimes.slashRU,returnEasing:s.attackReturnEasing.slashRU,inertia:+s.controls.inertia,spineTurn:+s.controls.spineTurn,boneInertia:s.attackBoneInertia.slashRU,worldInertia:s.attackInertiaTiming.slashRU.world,inertiaHold:s.attackInertiaTiming.slashRU.hold,inertiaDecay:s.attackInertiaTiming.slashRU.decay},end=m.attackSeconds,dt=1/meta.fps;
R.sample(m,end+.001,o);const tm=m.turnCache?.model||m,hand=m.names.indexOf('hand_r'),shoulder=m.names.indexOf('upperarm_r'),elbow=m.names.indexOf('lowerarm_r');
const at=t=>R.sample(m,t,o),endPose=at(end),rel=(p,j)=>R.sub(p.points[j],p.points[m.spine]),p0=rel(endPose,hand),p1=rel(at(end-dt),hand),p2=rel(at(end-2*dt),hand),v=R.mul(R.sub(p0,p1),1/dt),v1=R.mul(R.sub(p1,p2),1/dt),a=R.mul(R.sub(v,v1),1/dt),aN=R.sub(a,R.mul(R.unit(v),R.dot(a,R.unit(v)))),w=R.mul(R.cross(v,aN),1/R.dot(v,v));
const arc=t=>{const speed=R.length(w),angle=speed*t;return R.add(p0,speed<1e-6?R.mul(v,t):R.add(R.mul(v,Math.sin(angle)/speed),R.mul(R.cross(R.unit(w),v),(1-Math.cos(angle))/speed)));};
function predictFK(t,masked=false){const base=R.localize(at(end+t).points,at(end+t).q,m.parents),local=tm.locals.at(-1),q=[],points=[];for(let j=0;j<m.names.length;j++){const parent=m.parents[j];const active=tm.inertial[j]&&(!masked||(o.boneInertia[m.inertiaKeys[j]]??1)>0);q[j]=active?R.qm(R.qexp(R.mul(tm.worldVelocity[j],t)),endPose.q[j]):parent<0?base.q[j]:R.qm(q[parent],base.q[j]);const p=active?R.rotate(R.qexp(R.mul(tm.offsetVelocity[j],t)),local.p[j]):local.p[j];points[j]=parent<0?p:R.add(points[parent],R.rotate(q[parent],p));}return {q,points};}
const methods={current:t=>rel(at(end+t),hand),spring:t=>rel(R.sample(m,end+t,{...o,springReturn:true}),hand),worldFK:t=>rel(predictFK(t),hand),maskedWorldFK:t=>rel(predictFK(t,true),hand),arc};
const output={options:o,arc:{speed:R.length(v),omega:R.length(w),radius:R.length(v)/R.length(w),axis:R.unit(w)},methods:{}};
for(const [name,fn]of Object.entries(methods)){let prev=v;const rows=[];for(let i=1;i<=6;i++){const d=R.sub(fn(i*dt),fn((i-1)*dt)),speed=R.length(d)/dt,turn=Math.acos(Math.max(-1,Math.min(1,R.dot(R.unit(d),R.unit(prev)))))*180/Math.PI;const shoulderNow=rel(at(end+i*dt),shoulder),reach=R.length(R.sub(fn(i*dt),shoulderNow)),maxReach=R.length(R.sub(endPose.points[elbow],endPose.points[shoulder]))+R.length(R.sub(endPose.points[hand],endPose.points[elbow]));rows.push({i,stepCm:R.mul(d,100),speed,turn,reach,maxReach});prev=d;}output.methods[name]=rows;}
fs.writeFileSync(path.join(__dirname,'spring-study.json'),JSON.stringify(output,null,2));const cache=(m.turnCache?.model||m).springCache;output.springEndpoint={maxAngleDeg:Math.max(...cache.endpointBeforeSnap.q.map((q,j)=>R.length(R.qlog(R.qm(q,R.qinv(cache.frames.at(-1).q[j]))))*180/Math.PI)),handErrorCm:100*R.length(R.sub(R.fk(cache.endpointBeforeSnap,m.parents).points[hand],m.idlePose.points[hand]))};fs.writeFileSync(path.join(__dirname,'spring-study.json'),JSON.stringify(output,null,2));console.log(JSON.stringify({spring:output.methods.spring,endpoint:output.springEndpoint},null,2));
