from pathlib import Path
import re,json
base=Path('Saved/Diagnostics/GoldenRulesFix')
log=Path('Saved/Logs/GameAnimationSample3.log').read_text(encoding='utf-8',errors='replace');start=log.rfind('LogPython: GOLDEN_RULES_FINAL_RESET_CHECKS');segment=log[start:];(base/'tests-final-reset.log').write_text(segment,encoding='utf-8')
assert len(re.findall(r'Test Completed\. Result=\{Success\}',segment))==2
initial=(base/'tests-initial.log').read_text(encoding='utf-8');assert len(re.findall(r'Test Completed\. Result=\{Success\}',initial))==10
receipt={'loaded_utc':'2026-10-02 18:02:16','build':'Succeeded (Live Coding; normal DLL not rebuilt)','focused_checks_passed':10,'reset_checks_rerun_passed':2,'diagnostic_guard_checks_passed':3,'editor_restarted':False,'user_play_interrupted':False,'assets_explicitly_saved':False,'gameplay_capture_performed':False,'physics_solver_timing_changed':False}
(base/'receipt.json').write_text(json.dumps(receipt,indent=2),encoding='utf-8')
p=Path('ProjectJournal.md');s=p.read_text(encoding='utf-8');s=s.replace('October 2, validation pending','October 2, loaded and checked');s=s.replace('Live Coding build and focused checks pending, no restart;', 'Live Coding loaded 18:02:16 UTC; all 10 focused checks passed, with fist/mode reset checks passing again at 18:02:40 UTC. Diagnostic ownership/watchdog checks passed for all three scripts. Reset now completes fist/mode fades before removing their clocks. No Play capture, asset save or restart;');p.write_text(s,encoding='utf-8')
p=Path('Docs/GoldenRulesAuditFix20261002.md');s=p.read_text(encoding='utf-8');s=s.replace('Validation pending: Live Coding compile; targeted tick/fade/retirement tests. Python scripts parse successfully.', 'Validation: Live Coding build succeeded and loaded 18:02:16 UTC. All 10 focused tick/fade/retirement checks passed at 17:57:16 UTC; the two strengthened fist/mode reset checks passed again at 18:02:40 UTC. Reset completes these fades before removing their clocks, avoiding a stuck partial pose. All three Python scripts parse, reject replacement worlds and trigger their watchdogs in isolated guard checks. No gameplay replay: visual acceptance remains the user\'s test. Normal DLL rebuild remains required before cold launch. Receipts: Saved/Diagnostics/GoldenRulesFix/receipt.json, tests-initial.log, tests-final-reset.log, script-guards.json and build-final.log.');p.write_text(s,encoding='utf-8')
p=Path('Docs/KickPoleHandoffs20261002.md');s=p.read_text(encoding='utf-8');s=s.replace('169\u00e2\u20ac\u201c175','169–175');s=s.replace('Validation status: source changes implemented; Live Coding build and focused regression checks pending.', 'Validation: Live Coding loaded 18:02:16 UTC; independent pole-clock retirement, reconstruction fade, exact correction endpoints, calf-length and knee-handoff tests all passed. No new gameplay capture.');p.write_text(s,encoding='utf-8')
print(json.dumps(receipt))
