from pathlib import Path
p=Path('Docs/BlendTickTiming.md');s=p.read_text();s=s.replace('The NN still runs at its existing frequency.', 'The NN scheduler now receives exactly 1/60 authored second per unpaused game tick.\nAt the default 30 Hz policy this is one evaluation every two game ticks, including\nat 5 FPS or after a long hitch. Explicit per-agent locomotion rates are preserved;\nattack frames use the shared cadence. Engine timestamps identify pose samples only.\nAnimation-layer playback and all layer fades consume their own shared tick clock.\nFist closing/opening and simulation-mode transitions also use this clock.\nLegacy hand/target-pelvis inertia integrates the supplied fixed policy interval,\nnot differences between publication timestamps. The optional attack cone inherits\nthe fixed policy cadence. DoubleReach playback and smoothing spend at most one\n1/60 interval per game frame.\n\nThe NN retains its configured policy interval.')
s=s.replace('The FK timing fix does not rewrite the existing NN/physics scheduling, root\nintegration, pelvis bounds, attack/defense termination, animation playback or\nBlueprint graphs. This is a bounded implementation scope, not permission to\nintroduce wall-clock timing in future gameplay work.', 'The October 2 audit correction extends the earlier FK-only change to native NN\nscheduling, animation layers, fists, mode fades and DoubleReach. Physics solver\nstepping, external Sim Bridge delivery and Blueprint logic are unchanged; this\nis not a claim of fully deterministic rigid-body physics across FPS. Diagnostic\nwatchdogs and profiling use elapsed real time intentionally: they measure or stop\nthe tools and do not advance gameplay.')
p.write_text(s)
p=Path('Docs/KickPoleHandoffs20261002.md');s=p.read_text();s=s.replace('Investigation only. No runtime, Blueprint, checkpoint or tuning edits.', 'The measurements below describe the pre-fix baseline. The subsequent correction fades each procedural reconstruction with its existing blend clock, then retires it at zero. No Blueprint, checkpoint or tuning edits.')
s=s.replace('The correction should make the outgoing solved knee/thigh converge to the normal decoded leg before removing the recovery path; merely lengthening the pole limiter or damping physics would not address the discontinuous target construction. No fix or ablation rollout has been applied in this investigation.', 'The user requested simple existing-duration fades, with no convergence extension. Implemented: tempering reconstruction uses the remaining feet/pelvis blend weights; length reconstruction and presentation use the remaining length-return weight; the pole limiter fades to zero and retires at its configured deadline even if it was still limiting. Position lerps and shortest-arc rotation interpolation make the zero endpoint exactly the incoming NN pose. No new timer, smoothing state, duration pin or inference pass.')
s+='\nValidation status: source changes implemented; Live Coding build and focused regression checks pending. Visual acceptance remains the user’s test.\n';p.write_text(s)
p=Path('Docs/GoldenRulesAuditFix20261002.md');p.write_text('''# October 2 golden-rule audit corrections

Requested from the pasted audit while correcting kick recovery.

- Native NN scheduling: one fixed 1/60 budget per unpaused game tick, independent of frame delta and engine dilation. Default 30 Hz policy/attack cadence is every two game ticks. Custom locomotion rates remain explicit settings; no hitch backlog.
- Fists: manual and attack closing/opening use the shared bounded tick clock. Repeated pose reads spend no additional time; completed clocks retire.
- Simulation-mode changes: 15 game ticks for the existing .25 fade. Full captured pose/blend snapshots retire at the endpoint. Manual physical mode retains only its necessary nonphysical helper-bone locals, and the independent Chaos scale correction stays active.
- Animation layers: playback, blend-in and explicit blend-out use ticks since the last sample, rather than the number of policy evaluations. Replacing/stopping a layer retires its clock.
- Procedural motion: optional arm cone inherits fixed accepted-policy intervals. Legacy hand and target-pelvis inertia use supplied policy intervals instead of timestamp differences. DoubleReach playback, transition and motion-limit integration use one authored interval per game frame. No active DoubleReach instance existed in the editor when its proxy was changed.
- Disabled blood post effect: settings application disables its actor tick; inactive updates neither rebuild materials nor repeatedly scan Niagara. Existing enable/debug setters and property-edit hooks restart it. Direct C++ writes must call ApplyBloodFluidPostProcessSettings, as with other settings changes.
- Diagnostic scripts: sword, fist-deformation and interpolation tests require no existing Play session, track their owned world, stop only that world and have elapsed-time watchdogs. Fist/interpolation checkpoints now count observed game ticks so their assertions follow the new gameplay convention.

No Blueprint rewiring, asset saving, editor relaunch or physics solver scheduling changes. Profiling and diagnostic timeout clocks remain real-time measurements. External Sim Bridge delivery is not rewritten. This does not claim whole-physics determinism across FPS.

Validation pending: Live Coding compile; targeted tick/fade/retirement tests. Python scripts parse successfully. Source snapshots of the new audit changes are under Saved/Diagnostics/GoldenRulesFix/before; kick-fade snapshots are under Saved/Diagnostics/KickRecoveryFade/before.
''')
p=Path('ProjectJournal.md');s=p.read_text();a=s.index('- **Current kick knee-pole investigation');b=s.index('\n\n',a);s=s[:a]+'''- **Golden-rule audit + kick fade correction (October 2, validation pending):** native NN scheduling now receives one 1/60 authored budget per game tick; fist/mode/layer timing uses the shared tick clock; completed mode transitions retire full pose work; legacy hand/pelvis inertia uses fixed policy intervals; DoubleReach uses tick progression; blood effect disables its tick when off; three diagnostics enforce Play ownership and watchdogs. Kick reconstruction/pole/length corrections fade to zero on their existing durations with no convergence tail or new timer. No Blueprint tuning/wiring changes. Live Coding build and focused checks pending, no restart; normal DLL must be rebuilt before cold launch. [Audit correction](Docs/GoldenRulesAuditFix20261002.md), [kick baseline and correction](Docs/KickPoleHandoffs20261002.md).'''+s[b:]
s=s.replace('Existing NN/physics scheduling was not rewritten as part of that bounded fix.', 'The later October 2 audit correction also makes native NN scheduling tick-based. Physics solver scheduling remains separate; this rule does not assert whole-physics determinism.')
p.write_text(s)
