"""Bake original attack GT horizontal reach. Read-only with respect to Stepper.

Uses the same global_joint_pos cm / target metres contract as the final harness.
Training is Y-up; its X/Z plane maps to Unreal's X/Y plane.
"""
import argparse
import hashlib
import json
from pathlib import Path
import numpy as np

PROJECT = Path(__file__).resolve().parents[2]
DEFAULT_GT = Path('C:/Users/singerie/Documents/Cursor/stepper/training/slashes2/final_gt_attack_dataset_npz')
ATTACKS = ('jabL','jabR','hookL','hookR','overL','overR','headbutt','kickL','kickR',
           'slashL','slashR','slashLD','slashRD','slashLU','slashRU','pike')

def export(source):
    files = {p.stem.lower(): p for p in source.glob('*.npz')}
    rows = []
    for attack in ATTACKS:
        path = files[attack.lower()]
        with np.load(path, allow_pickle=False) as z:
            names = list(z['bone_names'])
            assert float(z['system_unit_scale_factor_cm']) == 1.
            assert int(z['frame_start']) == 0 and float(z['fps']) == 30.
            assert str(z['attack_clip']).lower() == attack.lower()
            feet = np.asarray(z['global_joint_pos'][0, [names.index('foot_l'),names.index('foot_r')]], dtype=np.float64)
            target = np.asarray(z['attack_target_world_m'], dtype=np.float64) * 100.
            midpoint = feet.mean(axis=0)
            delta = (target - midpoint)[[0,2]]
            radius = float(np.linalg.norm(delta))
            assert np.isfinite(feet).all() and np.isfinite(target).all() and radius > 0.
            rows.append(dict(attack=attack, source=str(path), sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
                first_frame_feet_cm=feet.tolist(), balance_center_xz_cm=midpoint[[0,2]].tolist(),
                gt_target_cm=target.tolist(), hit_frame=float(z['attack_hit_frame']), radius_cm=radius))
    data = dict(schema=1, reference='Frame 0 flat foot_l/foot_r midpoint to saved GT hit target; ignore training Y (height).',
                source_units='global_joint_pos: cm; attack_target_world_m: metres',
                families=rows, excluded='*_M mirror augmentation clips are not additional runtime attack families.')
    report = PROJECT/'Docs/AttackTargetReach.json'
    report.write_text(json.dumps(data,indent=2)+'\n')
    lines = ['// Generated by Tools/NN/ExportAttackTargetReach.py. Do not hand-edit.',
             '// Original GT frame-0 foot midpoint -> saved hit target, horizontal cm.',
             '// Source paths/hashes and raw coordinates: Docs/AttackTargetReach.json.',
             'namespace ProphecyAttackTargetReach', '{',
             'struct FEntry { FName Attack; double RadiusCm; };',
             'static const FEntry Entries[] = {']
    lines += ['    { TEXT("%s"), %.12f },' % (r['attack'],r['radius_cm']) for r in rows]
    lines += ['};','}']
    (PROJECT/'Source/GameAnimationSample3/Private/ProphecyAttackTargetReach.inl').write_text('\n'.join(lines)+'\n')
    for row in rows: print(f"{row['attack']:9s} {row['radius_cm']:9.4f} cm (with default extra: {row['radius_cm']+50:.4f})")

if __name__ == '__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--gt-dir',type=Path,default=DEFAULT_GT)
    export(parser.parse_args().gt_dir)
