// Export only accepted lab data and independent JS reference poses. No runtime JS/JSON work.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const project=path.resolve(__dirname,'../..');
const lab=process.argv[2]||'C:/Users/singerie/Documents/Cursor/stepper/training/slashes2/AttackRecoveryLab';
const R=require(path.join(lab,'recovery.js'));
const manifest=JSON.parse(fs.readFileSync(path.join(lab,'data/manifest.json')));
const state=JSON.parse(fs.readFileSync(path.join(lab,'state.json')));
const groups=['spine','clavicle','upperarm','lowerarm','neck_01','neck_02','head'];
const upper=manifest.names.map((name,j)=>({name,j})).filter(({j})=>{let p=j;while(p>=0){if(manifest.names[p]==='spine_01')return true;p=manifest.parents[p];}return false;});
if(upper.length!==16)throw Error('Unexpected upper hierarchy');
const idle=R.localize(manifest.sharedIdle.points,manifest.sharedIdle.axes.map(R.fromAxes),manifest.parents);
const uq=q=>[-q[0],q[1],-q[2],q[3]],up=p=>[p[0]*100,-p[1]*100,p[2]*100];
const literal=n=>{let s=Number(n).toPrecision(10);return s+'f';};
const profile=c=>({duration:state.attackReturnTimes[c.name],easing:state.attackReturnEasing[c.name],inertia:Number(state.controls.inertia),weights:groups.map(k=>state.attackBoneInertia[c.name][k])});
const rows=upper.map(({name,j})=>`    {TEXT("${name}"), TEXT("${manifest.names[manifest.parents[j]]}"), ${groups.indexOf(name.replace(/^spine_0[1-5]$/,'spine').replace(/_[lr]$/,''))<0?7:groups.indexOf(name.replace(/^spine_0[1-5]$/,'spine').replace(/_[lr]$/,''))}, {${uq(idle.q[j]).map(literal)}}, {${up(idle.p[j]).map(literal)}}},`);
const digest=crypto.createHash('sha256').update(fs.readFileSync(path.join(lab,'recovery.js'))).digest('hex');
const out=path.join(project,'Source/GameAnimationSample3/Private/ProphecyFKReturnData.h');
fs.writeFileSync(out,`#pragma once
// Generated by Tools/NN/ExportFKReturnLab.cjs. Canonical M_Neutral_Stand_Idle_Loop frame 0.
// Lab recovery.js SHA256 ${digest}. Parent-local S * R * S, S=diag(1,-1,1).
namespace ProphecyFKReturn::Data
{
struct FBone { const TCHAR* Name; const TCHAR* Parent; uint8 Group; float Q[4],P[3]; };
inline const FBone Bones[16]={
${rows.join('\n')}
};
struct FProfile { const TCHAR* Attack; float Duration,Easing,Inertia,Weights[7]; };
inline const FProfile Profiles[]={
${manifest.clips.map(c=>{const p=profile(c);return `    {TEXT("${c.name}"),${literal(p.duration)},${literal(p.easing)},${literal(p.inertia)},{${p.weights.map(literal)}}},`;}).join('\n')}
};
}
`);
// Include every generated variant, the extreme half-attack yaw directions, and zero inertia.
const cases=[];
const convert=pose=>pose.q.map((q,j)=>[...uq(q),...up(pose.points[j])]);
for(const c of manifest.clips)for(const v of c.variants){
 const buf=fs.readFileSync(path.join(lab,v.file));
 const m=R.prepare(v,buf.buffer.slice(buf.byteOffset,buf.byteOffset+buf.byteLength),c,manifest.names,manifest.parents);
 const p=profile(c),yaw=v===c.variants[0]?179:v===c.variants.at(-1)?-179:0;
 const opt={duration:p.duration,returnEasing:p.easing,inertia:p.inertia,boneInertia:state.attackBoneInertia[c.name],spineTurn:yaw};
 cases.push({name:c.name,variant:v.id||v.file,fps:v.fps,options:p,
  previous:convert(R.sample(m,m.attackSeconds-1/v.fps,{spineTurn:yaw})),current:convert(R.sample(m,m.attackSeconds,{spineTurn:yaw})),
  samples:[0,.001,.1,.25,.5,.75,.99,1].map(x=>({x,pose:convert(R.sample(m,m.attackSeconds+x*p.duration,opt))}))});
}
const fixture=path.join(project,'Saved/FKReturn/lab-reference.json');fs.mkdirSync(path.dirname(fixture),{recursive:true});
fs.writeFileSync(fixture,JSON.stringify({names:manifest.names,parents:manifest.parents,algorithmSha:digest,cases}));
console.log(JSON.stringify({header:out,fixture,cases:cases.length,profile:profile(manifest.clips[0])}));
