from pathlib import Path
p=Path('Docs/AttackStartPelvisInertia.md');s=p.read_text(encoding='utf-8');s=s.replace('Pending current build and native checks. The helper is called from the existing externally linked RecoveryCalfLength test, to ensure Live Coding executes the new assertions rather than retaining an old anonymous test implementation.', '''Normal editor build succeeded 2026-09-24 in 193.84 seconds. User authorized saving the pose Blueprint and restarting; save succeeded, clean Slate shutdown completed (the process lingered briefly, then exited on its own), and testNN reopened. Canonical reflected node invocation succeeds; pose Blueprint compiles with status 3, zero stale agent types and no default/wiring repairs needed. No new node was wired into the user's graph.

All six focused tests passed at 15:27:48 UTC: pelvis inertia geometry/motion, RecoveryCalfLength (including this feature's new checks and the existing knee regression), and presentation cadence/lifecycle. New checks cover exact previous world linear/angular increments, independent five/seven-tick retirement, repeated-read immunity, zero/disabled bypass, reset configuration/motion, root-carrier sampling, physical-world/component-space parity, preserved reachable feet and 1001 hip displacements. Maximum segment-length error was 2.14e-14 cm. Helper invocation through the existing external RecoveryCalfLength test emitted its unique receipt.

A short owned kinematic overL probe recorded 89 samples. First-frame linear delta error was exactly 0 cm, angular delta error 1.12e-16 radians; translation offset retired on tick 5 and rotation on tick 7 (independent double-precision reconstruction differs from the engine float-angle interpolation by about 1.3e-5 degrees). Physical mesh versus corrected target maximum position/rotation errors were 1.43e-14 cm / 2.48e-16 radians. This confirms target/presentation integration, not a general collision-response claim for simulated bodies. The temporary configuration and actor-tick override existed only in that diagnostic PIE, which ended without saving gameplay changes.

Evidence: `Saved/Diagnostics/AttackStartInertia-runtime.json`, `AttackStartInertia-verification.json`, native automation receipts in `Saved/Logs/GameAnimationSample3.log`. The normal build also incorporates preceding Live Coding source changes, including the still-pending knee recovery trial (mode 3).''');p.write_text(s,encoding='utf-8')
p=Path('ProjectJournal.md');s=p.read_text(encoding='utf-8');needle='## Working rules\n';entry='''
- **Attack-start pelvis inertia2026-09-24:** new per-agent `Set Attack Start Pelvis Inertia`: Enabled (off until configured), Translation Window Frames=5/Inertia=1, Rotation Window Frames=5/Inertia=1. New full attacks latch previous displayed WORLD linear/angular deltas; strength1 preserves them on frame1, linearly fades to authored target by each final frame. Windows0/1 or strength0 bypass that channel. Game-tick timing, no wall clock/extra inference/timer; disabled removes sampling/history/correction. Enabled keeps two pelvis-only samples. Shared render/physical/single-bone targets; FK follows pelvis, connected legs retain reachable feet and rotations. Raw checkpoint/root/attack latches unchanged; retriggers do not restart, half attacks retain locomotion pelvis. End/disable/reset cancel motion, reset restores captured settings. Six native tests passed15:27:48UTC; owned overL confirms exact first linear delta, angular error1.12e-16rad, independent5/7 retirement and mesh/target parity. User authorized BP save/restart; normal build193.84s succeeded, testNN reopened, BP status3/zero stale types, no graph wiring changes. This normal build includes preceding live patches; knee mode3 remains a trial pending acceptance. [Contract and evidence](Docs/AttackStartPelvisInertia.md).
''';assert needle in s;s=s.replace(needle,needle+entry,1);p.write_text(s,encoding='utf-8')
