from pathlib import Path
p=Path('Docs/AttackStartPelvisInertia.md');s=p.read_text();a=s.index('Foot extension and raw-limit removal:');b=s.index('\n\n## Earlier pelvis-only evidence',a)
s=s[:a]+'''Foot extension and raw-limit removal2026-09-24: authorized pose Blueprint save/restart completed, normal Editor build passed21.69s after correcting a remaining smoothing-veto reference. Added controls preserved old values/wiring and default feet to0; removed one live setter and reconnected execution. Blueprint status3, zero stale types; migrated asset saved. Eight pinning/presentation tests passed19:09:09UTC; the final entry/calf regression passed19:17:59UTC. Direct world-delta checks report position error0 and angular error0/5e-17; whole-transform equality was replaced by direct position/rotation-vector comparisons rather than treating a failed generic equality as motion error.

A short owned overL capture (89 samples) exposed pre-clamp ankle sampling. The final shared calf-correction sampling reduces first-entry left/right translation-delta error0.02248/0.09863cm to2.96e-7/3.55e-15cm. Both foot angular-delta errors are below2.4e-16 radians. Remaining mesh-versus-target positional differences up to0.1033/0.0597cm persist after the entry window as well; this is not a claim of exact full-scene mesh/target position parity or of physical collision-response quality. Native connected-geometry/component-world parity checks pass, along with unreachable projection, toe mounting, independent5/7 and4/6 retirement, feet-only configuration, duplicate updates and reset/disable.

Final runtime sampling fix is in Live Coding patch1 (168.90s build, loaded19:17:25UTC); include it in the next authorized normal build before a fresh launch. No reflected changes after the normal build. Owned Play ended, diagnostic actor references released, user foot strengths remain0. Evidence: `Saved/Diagnostics/FootEntryInertia-runtime.json`, `FootEntryInertia-verification.json`, `AttackEntryFootPins.txt`, `RemoveWalkPinLimit.txt`; prior saved BP backup `BP-BeforeFootEntryRestart.uasset`.
'''+s[b:];p.write_text(s)
p=Path('ProjectJournal.md');s=p.read_text(encoding='utf-8');s=s.replace('Blueprint existing values/wiring preserved; final sampling regression verification pending.','Blueprint old values/wiring preserved, status3/zero stale types, migrated asset saved. Eight pinning/presentation tests pass; final entry/calf test passed19:17:59UTC.89-sample owned overL first foot translation-delta errors2.96e-7/3.55e-15cm, angular errors<2.4e-16rad. Small existing mesh-target positional differences remain; no physical-response claim. Final private sampling correction is Live Coding patch1 (168.90s), to include in next authorized normal build; own Play ended/references released.');s=s.replace('Blueprint migration bypasses obsolete setter execution and removes those nodes; verification pending.','Blueprint migration removed one setter and reconnected execution; pose BP compiled status3 and saved. All six remaining Walk pinning tests pass. The smoothing residual-veto branch was also removed.');p.write_text(s,encoding='utf-8')
