from pathlib import Path
p=Path('ProjectJournal.md');s=p.read_text(encoding='utf-8')
entry='''- Combat return + root-speed auto run INSTALLED (2026-09-17): attack/defense return resets the registered magic cube to root XY, preserving height, zeroing cube UE/native velocities and first linear magic feedback; angular magic and set2 remain unchanged. No registered cube means no reset. Existing ordinary pelvis-bounds shifts retain their semantics. Attack inference failure paths now use common stop cleanup. Set/Get Locomotion Auto Run Speed Threshold is per-agent, default100000cm/s, choosing run above final root0->root1 planar speed AFTER smoothing/magic/limits, through existing blend times; it does not accelerate the mover. Sparse settings, no new tick or extra model execution. Live Coding318.39s, no restart. Three focused automation tests passed; physical-Jolt PIE smoke verified default100000, walk intent+300cm/s magic selecting100%run at threshold100, and attack stop producing exact0cm cube/root XY error with magic1 zero and magic2 preserved. See Docs/CombatContactInvestigation20260917.md.

  Collision diagnosis remains bounded: five controlled hooks recorded39 PhysicalMesh-vs-PhysicalMesh callbacks per agent, so the bridge works, but no complete missed head crossing was established. At X500/debug1false the tick90 sword jump was NOT reproduced; a startup61.61degree/frame rotation was reproduced. Moving the obstacle away reduced that startup spike;120Hz Discrete improved small later jitter but did not fix startup. Native CCD mode is already Discrete despite the sword component CCD checkbox. Official Jolt research recommends smaller collision timesteps for missed detection, distinguishes solver/slop tuning from detection, warns against excessive speculative distance; an Armed-only PHAT sweep is a possible separate gameplay-hit feature. No production CCD/quality/collider/drive change installed. Disposable test transforms, bool and physics settings restored; user BP/map left unsaved as found. Evidence Saved/Diagnostics/{HooksAttacks.json,SwordJump_*.json,CombatHandoffSmoke.json}.

'''
s=s.replace('# Prophecy Project Journal\n\n','# Prophecy Project Journal\n\n'+entry,1);p.write_text(s,encoding='utf-8')
p=Path('Saved/Diagnostics/CombatCollisionTasks.md');s=p.read_text(encoding='utf-8').replace('- [ ]','- [x]');s+='\nCompleted: see Docs/CombatContactInvestigation20260917.md. Hook phasing/tick90 sword jump not reproduced; documented bounded evidence and official non-CCD research, no speculative production collision fix. Required cube-reset and auto-run code installed/tested.\n';p.write_text(s,encoding='utf-8')
