from pathlib import Path
base=Path.cwd()
p=base/'Docs/NNDefense.md';s=p.read_text(encoding='utf-8')
s=s.replace('Attacker, Blocker (Blade / Left Arm / Right Arm), Maximum','Attacker, Maximum').replace(' Blade blocking requires a held sword.','')
s=s.replace('block/harmful contact, fractional contact time and collider','fractional contact time and collider (no block/harm classification)')
s=s.replace('Selected Parry blockers retain blocker-before-harm ordering.','The earliest confirmed contact ends defense regardless of the contacted limb; there is no selected blocking arm or success/damage classification.')
p.write_text(s,encoding='utf-8')
p=base/'Docs/LiveDefenseControls.md';s=p.read_text(encoding='utf-8').replace('predicted Blocked/HarmfulContact flags stay false, ContactCollider is None','ContactCollider is None')
p.write_text(s,encoding='utf-8')
p=base/'Saved/Diagnostics/DodgeMismatch/test_reverse_roles.py';s=p.read_text(encoding='utf-8')
s=s.replace(',harmful=d.harmful_contact,blocked=d.blocked','')
s=s.replace('Diagnostics/CombatReverseRoles/PIE.json','Diagnostics/RemoveParryBlocker/PIE.json')
s=s.replace('reverse=t>=3.1;dodge=t>=6.1','reverse=False;dodge=t>=2.5').replace('if t>=8.8','if t>=4.8')
(base/'Saved/Diagnostics/test_parry_without_blocker.py').write_text(s,encoding='utf-8')
